blog/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "blog"

urlpatterns = [
    # path("", views.index, name="index"),
    path("", views.HomeListView.as_view(), name="home"),
    path("search/", views.SearchListView.as_view(), name="search"),
    path("articles/", views.ArticleListView.as_view(), name="article_list"),
    path("article/<slug>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("articles/<filter>/", views.FilteredArticleListView.as_view(), name="filtered_article"),
    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path("categories/<slug>/", views.CategoryDetailView.as_view(), name="category_detail"),
    path("about/", views.AboutTemplateView.as_view(), name="about"),
    path("contact/", views.ContactUsView.as_view(), name="contact"),
]

meranda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.shortcuts import redirect, reverse

# Create your models here.


class Article(models.Model):
    author = models.ForeignKey("Author", on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=250)
    body = models.TextField()
    image = models.ImageField(upload_to="image/%y/%m/%d/", height_field="height_field", width_field="width_field", blank=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey("Category", on_delete=models.DO_NOTHING)
    tag = models.ManyToManyField("Tag", blank=True)
    view_count= models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    is_published = models.BooleanField(default=True)
    is_trending = models.BooleanField(default=False)
    is_editors_pick = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:article_detail", kwargs={"slug": self.slug})

    def get_read_time(self):
        """
        Get the estimated read time of an article
        """
        pass


class Author(models.Model):
    name = models.CharField(max_length=150)
    summary = models.TextField()
    date_joined = models.DateTimeField(auto_now=False, auto_now_add=True)
    image = models.ImageField(upload_to="image/%y/%m/%d/", blank=True)
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:author_detail", kwargs={"pk": self.pk})


class Category(models.Model):
    name = models.CharField(max_length=150)
    summary = models.TextField()
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    is_featured = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:category_detail", kwargs={"slug": self.slug})


class Tag(models.Model):
    """
    Tags that have a many to many field relationship to article
    """
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    

class Contact(models.Model):
    first_name = models.CharField(max_length=150, null=True)
    last_name = models.CharField(max_length=150, null=True)
    email = models.CharField(max_length=150)
    phone = models.CharField(max_length=150, null=True)
    message = models.TextField()
    
    def __str__(self):
        identity = f"{self.first_name} {self.last_name} : {self.email}"
        return identity
    

blog/forms.py
from django import forms


class ContactUsForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}), label="First Name", max_length=200, required=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}), label="Last Name", max_length=200, required=False)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}), label="Email Address")
    phone = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}), label="Tel. Number", required=False)
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

blog/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, DeleteView, View
from .forms import ContactUsForm
from .models import Article, Category, Contact

# Create your views here.


class SearchListView(ListView):
    paginate_by = 15
    template_name = "blog/search_list.html"

    def get_queryset(self):
        query = self.request.GET.get('q')
        try:
            category_list_initial = Category.objects.filter(name__icontains=query)[0]
        except:
            category_list_initial = 0
        object_list = Article.objects.filter(Q(title__icontains=query) | Q(category=category_list_initial))
        return object_list

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('q')
        queryset = Article.objects.order_by("-timestamp")
        queryset_popular = Article.objects.order_by("-view_count")
        cat_query = Category.objects.all()
        
        context = super().get_context_data(**kwargs)
        context["popular_articles"] = queryset_popular[:4]
        context["categories"] = cat_query
        context["query"] = query
        
        return context

        

# def search(request):

#     pass
        

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["query"] = self.request.GET.get('q')
#         return context


class HomeListView(ListView):
    model = Article
    template_name = "blog/index.html"

    def get_context_data(self, **kwargs):
        queryset = Article.objects.order_by("-timestamp")
        queryset_popular = Article.objects.order_by("-view_count")
        queryset_editors_pick = queryset.filter(is_editors_pick=True)
        queryset_is_trending = queryset.filter(is_trending=True)
        cat_query = Category.objects.all()
        featured_cat_query = cat_query.filter(is_featured=True)
        featured_editors_pick_query = queryset.filter(is_featured=True, is_editors_pick=True)

        
        featured_cat_1 = featured_cat_query[0]
        featured_cat_2 = featured_cat_query[1]
        trending_category_1 = queryset.filter(category=featured_cat_1)
        trending_category_2 = queryset.filter(category=featured_cat_2)
        

        context = super().get_context_data(**kwargs)
        context["recent_articles"] = queryset[:4]
        context["popular_articles"] = queryset_popular[:4]
        context["categories"] = cat_query

        context["editors_pick_1"] = queryset_editors_pick[0]
        context["editors_picks"] = queryset_editors_pick[1:4]
        context["trending_articles"] = queryset_is_trending[:4]


        context["featured_category_1"] = featured_cat_1.name
        context["featured_category_2"] = featured_cat_2.name
        context["featured_category_article_1"] = trending_category_1[:3]
        context["featured_category_article_2"] = trending_category_2[:3]
        
    
        context["featured_editors_pick_1"] = featured_editors_pick_query[0]
        context["featured_editors_pick_2"] = featured_editors_pick_query[1]
        context["featured_editors_pick_3"] = featured_editors_pick_query[2]
        
        return context


class ArticleListView(ListView):
    model = Article
    paginate_by = 6
    template_name = "blog/article_list.html"

    def get_context_data(self, **kwargs):
        queryset = Article.objects.order_by("-timestamp")
        queryset_popular = Article.objects.order_by("-view_count")
        cat_query = Category.objects.all()
        
        context = super().get_context_data(**kwargs)
        context["popular_articles"] = queryset_popular[:4]
        context["categories"] = cat_query
        
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = "blog/article_detail.html"   

    def get_context_data(self, **kwargs):
        queryset = Article.objects.order_by("-timestamp")
        queryset_popular = Article.objects.order_by("-view_count")
        cat_query = Category.objects.all()
        current = queryset.filter(title=kwargs['object'])[0]
        if current:
            current.view_count += 1
            current.save()
        context = super().get_context_data(**kwargs)
        context["popular_articles"] = queryset_popular[:4]
        context["categories"] = cat_query
        
        return context


class CategoryListView(ListView):
    model = Category
    paginate_by = 20
    template_name = "blog/category_list.html"

    def get_context_data(self, **kwargs):
        queryset = Article.objects.order_by("-timestamp")
        queryset_popular = Article.objects.order_by("-view_count")
        cat_query = Category.objects.all()
        
        context = super().get_context_data(**kwargs)
        context["popular_articles"] = queryset_popular[:4]
        context["categories"] = cat_query
        
        return context


class CategoryDetailView(TemplateView):
    # model = Category
    # paginate_by = 9
    template_name = "blog/category_detail.html"

    def get_context_data(self, *args, **kwargs):
        slugged_category = Category.objects.all().filter(slug=kwargs['slug'])[0]
        queryset_by_category = Article.objects.order_by("-timestamp").filter(category=slugged_category)
        
        paginator = Paginator(queryset_by_category, 9)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        queryset_popular = Article.objects.order_by("-view_count")
        cat_query = Category.objects.all()
        
        context = super().get_context_data(**kwargs)
        context["popular_articles"] = queryset_popular[:4]
        context["categories"] = cat_query
        context["page_obj"] = page_obj
        context["slugged_category"] = slugged_category
        
        return context


# class CategoryDetailView(View):

#     def get(self, *args, **kwargs):
#         # queryset_by_category = Article.objects.order_by("-timestamp").filter(category__icontains=kwargs)
#         qq = Article.category
#         print(qq)
#         queryset_by_category = Article.objects.order_by("-timestamp").filter(category=kwargs)
#         queryset_popular = Article.objects.order_by("-view_count")
#         cat_query = Category.objects.all()
#         return render(self.request, 'blog/category_detail.html', {'category_queryset': queryset_by_category})

# def category_detail(request, slug):
#     category.objects.all().filter(slug=slug)


class ContactUsView(View):

    # def get_context_data(self, **kwargs):
    #     queryset = Article.objects.order_by("-timestamp")
    #     queryset_popular = Article.objects.order_by("-view_count")
    #     cat_query = Category.objects.all()
        
    #     context = super().get_context_data(**kwargs)
    #     context["popular_articles"] = queryset_popular[:4]
    #     context["categories"] = cat_query
        
    #     return context

    def get(self, *args, **kwargs):
        form = ContactUsForm()
        template_name = "blog/contact.html"
        queryset = Article.objects.order_by("-timestamp")
        queryset_popular = Article.objects.order_by("-view_count")
        cat_query = Category.objects.all()
        context = {
            "form": form,
            "popular_articles": queryset_popular[:4],
            "categories": cat_query
            }
        return render(self.request, template_name, context)

    def post(self, *args, **kwargs):
        form = ContactUsForm(self.request.POST or None)
        contact = Contact()
        if form.is_valid():
            # print(form.cleaned_data)
            contact.first_name = form.cleaned_data['first_name']
            contact.last_name = form.cleaned_data['last_name']
            contact.email = form.cleaned_data['email']
            contact.phone = form.cleaned_data['phone']
            contact.message = form.cleaned_data['message']

            recipents = ['judeakinwale@gmail.com']
            # name = f"{first_name} {last_name}"
            # print("name")
            contact.save()
            # send_mail(name, message, email, recipents)
            return redirect("blog:home")
        return redirect("blog:contact")


# def get_name(request):
#     # if this is a POST request we need to process the form data
#     if request.method == 'POST':
#         # create a form instance and populate it with data from the request:
#         form = NameForm(request.POST)
#         # check whether it's valid:
#         if form.is_valid():
#             # process the data in form.cleaned_data as required
#             # ...
#             # redirect to a new URL:
#             return HttpResponseRedirect('/thanks/')
#     # if a GET (or any other method) we'll create a blank form
#     else:
#         form = ContactUsForm()
#     return render(request, 'name.html', {'form': form})

class FilteredArticleListView(TemplateView):
    template_name = "blog/filtered_article_list.html"

    def get_context_data(self, **kwargs):
        print(kwargs)
        if "popular" in kwargs['filter']:
            query = "Popular"
            queryset = Article.objects.order_by("-view_count")
            side_title = "Trending"
            side_articles = Article.objects.order_by("-timestamp").filter(is_trending=True)
        elif "trending" in kwargs['filter']:
            query = "Trending"
            queryset = Article.objects.order_by("-timestamp").filter(is_trending=True)
            side_title = "Popular"

blog/templates/blog/about.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-12 text-left">
                <div class="section-title mb-5">
                    <h2>About Us</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <p>
                    <img src="{% static 'images/about.jpg' %}" alt="Image" class="img-fluid">
                </p>
            </div>
            <div class="col-lg-6 pl-md-5">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam qui obcaecati eaque odio, alias nulla
                    quae, aliquid, rerum consequuntur, quaerat blanditiis cupiditate eos doloribus dolor debitis! Ex
                    eius deleniti, soluta!</p>
                <p>Facilis sit molestiae deserunt quo corporis culpa dolorum animi architecto illum sapiente.
                    Asperiores, placeat animi distinctio provident adipisci.</p>
                <ul class="ul-check list-unstyled success mt-5">
                    <li>Lorem ipsum dolor sit.</li>
                    <li>Cupiditate dolores rerum, consequatur!</li>
                    <li>Quia dolor molestias voluptatem?</li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h2>Editor's Pick</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% if editors_pick_1 %}
                    <div class="col-md-6">
                        <!-- Most Recent Editors Pick -->
                        <div class="post-entry-1">
                            <a href="{{editors_pick_1.get_absolute_url}}"><img src="{{editors_pick_1.image.url}}" alt="Image"
                                    class="img-fluid"></a>
                            <h2><a href="{{editors_pick_1.get_absolute_url}}">{{editors_pick_1.title}}</a></h2>
                            <p class="text-truncate">{{editors_pick_1.body}}</p>
                            <div class="post-meta">
                                <span class="d-block"><a href="#">{{editors_pick_1.author}}</a> in <a
                                        href="#">{{editors_pick_1.category}}</a></span>
                                <span class="date-read">{{editors_pick_1.timestamp|date:"M d"}} <span class="mx-1">&bullet;</span> 3
                                    min read
                                    <span class="icon-star2"></span></span>
                                <!-- <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span
                                                                                            class="icon-star2"></span></span> -->
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        {% for article in editors_picks %}
                        <div class="post-entry-2 d-flex bg-light">
                            <div class="thumbnail" style="background-image: url('../../../../.{{article.image.url}}')"></div>
                            <div class="contents">
                                <h2><a href="blog-single.html">{{article.title}}</a></h2>
                                <div class="post-meta">
                                    <span class="d-block"><a href="#">{{article.author}}</a> in <a
                                            href="#">{{article.category}}</a></span>
                                    <span class="date-read">{{article.timestamp|date:"M d"}} <span class="mx-1">&bullet;</span> 3
                                        min read
                                        <span class="icon-star2"></span></span>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% else %}
                    <h2>There are no Editor's picks yet</h2>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <div class="section-title">
                    <h2>Trending</h2>
                </div>
                {% if trending_articles %}
            
                {% for article in trending_articles %}
                <div class="trend-entry d-flex">
                    <div class="number align-self-start">0{{forloop.counter}}</div>
                    <div class="trend-contents">
                        <h2><a href="{{article.get_absolute_url}}">{{article.title}}</a></h2>
                        <div class="post-meta">
                            <span class="d-block"><a href="#">{{article.author}}</a> in <a href="#">{{article.category}}</a></span>
                            <span class="date-read">{{article.timestamp|date:"M d"}} <span class="mx-1">&bullet;</span> 3 min read
                                <span class="icon-star2"></span></span>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <p><a href="{% url 'blog:filtered_article' 'trending' %}" class="more">See All Trends <span
                            class="icon-keyboard_arrow_right"></span></a></p>
                {% else %}
                <div class="trend-entry d-flex">
                    <div class="trend-contents">
                        <h2>There are no trending articles yet</h2>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- END section -->
{% endblock content %}
    

blog/templates/blog/article_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="section-title">
                    <span class="caption d-block small">Categories</span>
                    <h2>All Categories</h2>
                </div>
                
                {% for article in object_list %}
                    <div class="post-entry-2 d-flex">
                        <div class="thumbnail order-md-2" style="background-image: url('../../../../.{{article.image.url}}')"></div>
                        <div class="contents order-md-1 pl-0">
                            <h2><a href="{{article.get_absolute_url}}">{{article.title}}</a></h2>
                            <p class="mb-3 text-truncate">{{article.body}}</p>
                            <div class="post-meta">
                                <span class="d-block"><a href="#">{{article.author}}</a> in <a href="#">{{article.category}}</a></span>
                                <span class="date-read">{{article.timestamp|date:"M d"}} <span class="mx-1">&bullet;</span> 3 min read <span
                                        class="icon-star2"></span></span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                    
                <!-- <div class="post-entry-2 d-flex">
                    <div class="thumbnail order-md-2" style="background-image: url('images/img_h_4.jpg')"></div>
                    <div class="contents order-md-1 pl-0">
                        <h2><a href="blog-single.html">News Needs to Meet Its Audiences Where They Are</a></h2>
                        <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi temporibus
                            praesentium neque, voluptatum quam quibusdam.</p>
                        <div class="post-meta">
                            <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                            <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span
                                    class="icon-star2"></span></span>
                        </div>
                    </div>
                </div> -->

            </div>
            <div class="col-lg-3">
                <div class="section-title">
                    <h2>Popular Posts</h2>
                </div>
            
                {% if popular_articles %}
            
                    {% for article in popular_articles %}
                        <div class="trend-entry d-flex">
                            <div class="number align-self-start">0{{forloop.counter}}</div>
                            <div class="trend-contents">
                                <h2><a href="{{article.get_absolute_url}}">{{article.title}}</a></h2>
                                <div class="post-meta">
                                    <span class="d-block"><a href="#">{{article.author}}</a> in <a href="#">{{article.category}}</a></span>
                                    <span class="date-read">{{article.timestamp|date:"M d"}} <span class="mx-1">&bullet;</span> 3 min read
                                        <span class="icon-star2"></span></span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
            
                    <p><a href="{% url 'blog:filtered_article' 'popular' %}" class="more">See All Popular <span class="icon-keyboard_arrow_right"></span></a></p>
                {% else %}
                <div class="trend-entry d-flex">
                    <div class="trend-contents">
                        <h2>There are no articles at this time. Please check back later</h2>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>

        {% if is_paginated %}
        <div class="row">
            <div class="col-lg-6">
                <ul class="custom-pagination list-unstyled">
        
                    {% if page_obj.has_previous %}
        
                        {% if page_obj.previous_page_number == 1 %}
                            <li><a href="?page=1">1</a></li>
                            {% else %}
                            <li><a href="?page=1">1</a></li>
                            <li><a href="?page={{page_obj.previous_page_number}}">{{page_obj.previous_page_number}}</a></li>
                        {% endif %}
        
                    {% endif %}
        
                    <li class="active"><a href="?page={{page_obj.number}}">{{page_obj.number}}</a></li>
        
                    {% if page_obj.has_next %}
            
                        {% if page_obj.next_page_number == page_obj.num_pages %}
                            <li><a href="?page={{page_obj.num_pages}}">{{page_obj.num_pages}}</a></li>
                            {% else %}
                            <li><a href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a></li>
                            <li><a href="?page={{page_obj.num_pages}}">{{page_obj.num_pages}}</a></li>
                        {% endif %}
        
                    {% endif %}
        
                </ul>
            </div>
        </div>
        {% endif %}
    </div>
</div>
<!-- END section -->
{% endblock content %}

blog/templates/blog/category_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="section-title">
                        <span class="caption d-block small">Find articles of a specific category</span>
                        <h2>All Categories</h2>
                    </div>
                    
                    {% for category in object_list %}
                        <div class="post-entry-2 d-flex">
                            <div class="contents order-md-1 pl-0">
                                <h2><a href="{{category.get_absolute_url}}">{{category}}</a></h2>
                            </div>
                        </div>
                    {% endfor %}
                        
                </div>
                <div class="col-lg-3">
                    <div class="section-title">
                        <h2>Popular Posts</h2>
                    </div>
                
                    {% if popular_articles %}
                
                    {% for article in popular_articles %}
                    <div class="trend-entry d-flex">
                        <div class="number align-self-start">0{{forloop.counter}}</div>
                        <div class="trend-contents">
                            <h2><a href="{{article.get_absolute_url}}">{{article.title}}</a></h2>
                            <div class="post-meta">
                                <span class="d-block"><a href="#">{{article.author}}</a> in <a href="#">{{article.category}}</a></span>
                                <span class="date-read">{{article.timestamp|date:"M d"}} <span class="mx-1">&bullet;</span> 3 min read
                                    <span class="icon-star2"></span></span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                
                    <p><a href="{% url 'blog:filtered_article' 'popular' %}" class="more">See All Popular <span class="icon-keyboard_arrow_right"></span></a></p>
                    {% else %}
                    <div class="trend-entry d-flex">
                        <div class="trend-contents">
                            <h2>There are no articles at this time. Please check back later</h2>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>

            {% if is_paginated %}
            <div class="row">
                <div class="col-lg-6">
                    <ul class="custom-pagination list-unstyled">
            
                        {% if page_obj.has_previous %}
            
                        {% if page_obj.previous_page_number == 1 %}
                        <li><a href="?page=1">1</a></li>
                        {% else %}
                        <li><a href="?page=1">1</a></li>
                        <li><a href="?page={{page_obj.previous_page_number}}">{{page_obj.previous_page_number}}</a></li>
                        {% endif %}
            
                        {% endif %}
            
                        <li class="active"><a href="?page={{page_obj.number}}">{{page_obj.number}}</a></li>
            
                        {% if page_obj.has_next %}
            
                        {% if page_obj.next_page_number == page_obj.num_pages %}
                        <li><a href="?page={{page_obj.num_pages}}">{{page_obj.num_pages}}</a></li>
                        {% else %}
                        <li><a href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a></li>
                        <li><a href="?page={{page_obj.num_pages}}">{{page_obj.num_pages}}</a></li>
                        {% endif %}
            
                        {% endif %}
            
                    </ul>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    <!-- END section -->
{% endblock content %}